export type FactStatus = "ALLEGATION"|"INQUIRY"|"FINDING"|"CONVICTION"|"CIVIL_JUDGMENT"|"PROGRAM_RISK";
export type FactKind = "CONTRACT"|"GRANT"|"DONATION"|"WATCHDOG_ACTION"|"COURT_OUTCOME"|"FOI_RELEASE"|"PROGRAM_ALERT";
